PustokP201/PustokP201/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PustokP201.Models;
using PustokP201.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PustokP201.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        private readonly PustokContext _context;

        public HeaderViewComponent(PustokContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            HeaderViewModel headerVM = new HeaderViewModel
            {
                Genres = await _context.Genres.ToListAsync(),
                Settings = await _context.Settings.ToListAsync()
            };
            return View(headerVM);
        }
    }
}

PustokP201/PustokP201/Views/Shared/_BookTabSlider.cshtml
@model  List<Book>

<div class="product-slider multiple-row  slider-border-multiple-row  sb-slick-slider"
     data-slick-setting='{
                                        "autoplay": true,
                                        "autoplaySpeed": 8000,
                                        "slidesToShow": 5,
                                        "rows":1,
                                        "dots":true
                                    }' data-slick-responsive='[
                                        {"breakpoint":1200, "settings": {"slidesToShow": 3} },
                                        {"breakpoint":768, "settings": {"slidesToShow": 2} },
                                        {"breakpoint":480, "settings": {"slidesToShow": 1} },
                                        {"breakpoint":320, "settings": {"slidesToShow": 1} }
                                    ]'>
    @foreach (Book item in Model)
    {
        <div class="single-slide">
            <div class="product-card">
                <div class="product-header">
                    <a href="#" class="author">
                        @item.Author.FullName
                    </a>
                    <h3>
                        <a href="product-details.html">
                            @item.Name
                        </a>
                    </h3>
                </div>
                <div class="product-card--body">
                    <div class="card-image">
                        <img src="~/image/products/@item.BookImages.FirstOrDefault(x=>x.PosterStatus==true)?.Image" alt="">
                        <div class="hover-contents">
                            <a href="product-details.html" class="hover-image">
                                <img src="~/image/products/@item.BookImages.FirstOrDefault(x=>x.PosterStatus==false)?.Image" alt="">
                            </a>
                            <div class="hover-btns">
                                <a asp-action="addbasket" asp-controller="book" asp-route-bookId="@item.Id" class="single-btn add-basket">
                                    <i class="fas fa-shopping-basket"></i>
                                </a>
                                <a href="wishlist.html" class="single-btn">
                                    <i class="fas fa-heart"></i>
                                </a>
                                <a href="compare.html" class="single-btn">
                                    <i class="fas fa-random"></i>
                                </a>
                                <a href="#" data-toggle="modal" data-id="@item.Id" 
                                   class="single-btn single-eye-btn">
                                    <i class="fas fa-eye"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="price-block">
                        @if (item.DiscountPercent > 0)
                        {
                            <span class="price">£@((item.SalePrice*(100-item.DiscountPercent)/100).ToString("#.00"))</span>
                            <del class="price-old">£@item.SalePrice</del>
                            <span class="price-discount">@item.DiscountPercent%</span>
                        }
                        else
                        {
                            <span class="price">£@item.SalePrice</span>
                        }

                    </div>
                </div>
            </div>
        </div>
    }
</div>

PustokP201/PustokP201/Views/Shared/_Layout.cshtml
@using PustokP201.Services 
@inject LayoutService service
@{ 
    List<Setting> settings = await service.GetSettings();

}
<!DOCTYPE html>
<html lang="zxx">


<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Pustok - Book Store HTML Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Use Minified Plugins Version For Fast Page Load -->
    <link rel="stylesheet" type="text/css" media="screen" href="~/css/plugins.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="~/css/main.css" />
    <link rel="shortcut icon" type="~/image/x-icon" href="~/image/favicon.ico">
</head>

<body>
    <div class="site-wrapper" id="top">
       
        @await Component.InvokeAsync("Header")

        @RenderBody()
    </div>
    <!--=================================
    Brands Slider
    ===================================== -->
    <section class="section-margin">
        <h2 class="sr-only">Brand Slider</h2>
        <div class="container">
            <div class="brand-slider sb-slick-slider border-top border-bottom" data-slick-setting='{
                                            "autoplay": true,
                                            "autoplaySpeed": 8000,
                                            "slidesToShow": 6
                                            }' data-slick-responsive='[
                {"breakpoint":992, "settings": {"slidesToShow": 4} },
                {"breakpoint":768, "settings": {"slidesToShow": 3} },
                {"breakpoint":575, "settings": {"slidesToShow": 3} },
                {"breakpoint":480, "settings": {"slidesToShow": 2} },
                {"breakpoint":320, "settings": {"slidesToShow": 1} }
            ]'>
                <div class="single-slide">
                    <img src="~/image/others/brand-1.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/image/others/brand-2.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/image/others/brand-3.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/image/others/brand-4.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/image/others/brand-5.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/image/others/brand-6.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/image/others/brand-1.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/image/others/brand-2.jpg" alt="">
                </div>
            </div>
        </div>
    </section>
    <!--=================================
    Footer Area
    ===================================== -->
    <footer class="site-footer">
        <div class="container">
            <div class="row justify-content-between  section-padding">
                <div class=" col-xl-3 col-lg-4 col-sm-6">
                    <div class="single-footer pb--40">
                        <div class="brand-footer footer-title">
                            <img src="~/image/@settings.FirstOrDefault(x=>x.Key == "FooterLogo")?.Value" alt="">
                        </div>
                        <div class="footer-contact">
                            <p>
                                <span class="label">Address:</span><span class="text">
                                    @settings.FirstOrDefault(x=>x.Key == "Address")?.Value
                                </span>
                            </p>
                            <p><span class="label">Phone:</span><span class="text">@settings.FirstOrDefault(x=>x.Key=="ContactPhone")?.Value</span></p>
                            <p><span class="label">Email:</span><span class="text">@settings.FirstOrDefault(x=>x.Key == "Email")?.Value</span></p>
                        </div>
                    </div>
                </div>
                <div class=" col-xl-3 col-lg-2 col-sm-6">
                    <div class="single-footer pb--40">
                        <div class="footer-title">
                            <h3>Information</h3>
                        </div>
                        <ul class="footer-list normal-list">
                            <li><a href="#">Prices drop</a></li>
                            <li><a href="#">New products</a></li>
                            <li><a href="#">Best sales</a></li>
                            <li><a href="#">Contact us</a></li>
                            <li><a href="#">Sitemap</a></li>
                        </ul>
                    </div>
                </div>
                <div class=" col-xl-3 col-lg-2 col-sm-6">
                    <div class="single-footer pb--40">
                        <div class="footer-title">
                            <h3>Extras</h3>
                        </div>
                        <ul class="footer-list normal-list">
                            <li><a href="#">Delivery</a></li>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Stores</a></li>
                            <li><a href="#">Contact us</a></li>
                            <li><a href="#">Sitemap</a></li>
                        </ul>
                    </div>
                </div>
                <div class=" col-xl-3 col-lg-4 col-sm-6">
                    <div class="footer-title">
                        <h3>Newsletter Subscribe</h3>
                    </div>
                    <div class="newsletter-form mb--30">
                        <form action="https://demo.hasthemes.com/pustok-preview/pustok/php/mail.php">
                            <input type="email" class="form-control" placeholder="Enter Your Email Address Here...">
                            <button class="btn btn--primary w-100">Subscribe</button>
                        </form>
                    </div>
                    <div class="social-block">
                        <h3 class="title">STAY CONNECTED</h3>
                        <ul class="social-list list-inline">
                            <li class="single-social facebook">
                                <a href="#"><i class="ion ion-social-facebook"></i></a>
                            </li>
                            <li class="single-social twitter"><a href="#"><i class="ion ion-social-twitter"></i></a></li>
                            <li class="single-social google">
                                <a href="#">
                                    <i class="ion ion-social-googleplus-outline"></i>
                                </a>
                            </li>
                            <li class="single-social youtube"><a href="#"><i class="ion ion-social-youtube"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <p class="copyright-heading">
                    Suspendisse in auctor augue. Cras fermentum est ac fermentum tempor. Etiam
                    vel
                    magna volutpat, posuere eros
                </p>
                <a href="#" class="payment-block">
                    <img src="~/image/icon/payment.png" alt="">
                </a>
                <p class="copyright-text">
                    Copyright © 2019 <a href="#" class="author">Pustok</a>. All Right Reserved.
                    <br>
                    Design By Pustok
                </p>
            </div>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Use Minified Plugins Version For Fast Page Load -->
    <script src="~/js/plugins.js"></script>
    <script src="~/js/ajax-mail.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/js/main.js"></script>
</body>


</html>

PustokP201/PustokP201/Views/Shared/_ModalBookDetail.cshtml
@model Book

<button type="button" class="close modal-close-btn ml-auto" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
</button>
<div class="product-details-modal">
    <div class="row">
        <div class="col-lg-5">
            <!-- Product Details Slider Big Image-->
            <div class="single-slide">
                <img src="~/image/products/@Model.BookImages.FirstOrDefault(x=>x.PosterStatus==true)?.Image" alt="">
            </div>
        </div>
        <div class="col-lg-7 mt--30 mt-lg--30">
            <div class="product-details-info pl-lg--30 ">
                <p class="tag-block">
                    Tags:

                    @for (int i = 0; i < Model.BookTags.Count; i++)
                    {
                        <a href="#">@Model.BookTags[i].Tag.Name @(i<Model.BookTags.Count-1?",":"")</a>
                    }

                </p>
                <h3 class="product-title">@Model.Name</h3>
                <ul class="list-unstyled">
                    <li>Ex Tax: <span class="list-value"> £60.24</span></li>
                    <li>Brands: <a href="#" class="list-value font-weight-bold"> @Model.Genre.Name</a></li>
                    <li>Product Code: <span class="list-value"> @Model.Code</span></li>
                    <li>Availability: <span class="list-value"> @(Model.StockStatus?"In Stock":"Out Stock")</span></li>
                </ul>
                <div class="price-block">
                    @if (Model.DiscountPercent > 0)
                    {
                    <span class="price-new">£@((Model.SalePrice*(100- Model.DiscountPercent)/100).ToString("#.00"))</span>
                        <del class="price-old">£@Model.SalePrice</del>
                    }
                    else
                    {
                        <span class="price-new">£@Model.SalePrice</span>
                    }

                </div>
                <div class="rating-widget">
                    <div class="rating-block">
                        <span class="fas fa-star star_on"></span>
                        <span class="fas fa-star star_on"></span>
                        <span class="fas fa-star star_on"></span>
                        <span class="fas fa-star star_on"></span>
                        <span class="fas fa-star "></span>
                    </div>
                    <div class="review-widget">
                        <a href="#">(1 Reviews)</a> <span>|</span>
                        <a href="#">Write a review</a>
                    </div>
                </div>
                <article class="product-details-article">
                    <h4 class="sr-only">Product Summery</h4>
                    <p>
                       @Model.Desc
                    </p>
                </article>
                <div class="add-to-cart-row">
                    <div class="count-input-block">
                        <span class="widget-label">Qty</span>
                        <input type="number" class="form-control text-center" value="1">
                    </div>
                    <div class="add-cart-btn">
                        <a href="#" class="btn btn-outlined--primary">
                            <span class="plus-icon">+</span>Add to Cart
                        </a>
                    </div>
                </div>
                <div class="compare-wishlist-row">
                    <a href="#" class="add-link"><i class="fas fa-heart"></i>Add to Wish List</a>
                    <a href="#" class="add-link"><i class="fas fa-random"></i>Add to Compare</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <div class="widget-social-share">
        <span class="widget-label">Share:</span>
        <div class="modal-social-share">
            <a href="#" class="single-icon"><i class="fab fa-facebook-f"></i></a>
            <a href="#" class="single-icon"><i class="fab fa-twitter"></i></a>
            <a href="#" class="single-icon"><i class="fab fa-youtube"></i></a>
            <a href="#" class="single-icon"><i class="fab fa-google-plus-g"></i></a>
        </div>
    </div>
</div>